<<<<<<< HEAD
# Generated by Django 3.2.15 on 2022-09-23 14:59
=======
# Generated by Django 3.2.15 on 2022-09-22 21:22
>>>>>>> origin/main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220911_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
<<<<<<< HEAD
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
=======
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
>>>>>>> origin/main
        ),
    ]
